# Classification {#sec-classification}

One of the long--standing problem in FRB research is the question on whether all bursts are the same or do they have different types?
Solving this problem will be a huge leap in understanding the true nature of FRB progenitors.
Determining whether or not FRBs have subclasses will help narrow down progenitor models and speed up the search.

## Repeating FRB {#sec-class-repeating}

Early searches for FRB found that bursts do not repeat [@lorimer_bright_2007; @petroff_fast_2019].
However, @spitler_RepeatingFastRadio_2016 found ten additional bursts coming from the source of FRB 121102.
This discovery leads to another question being raised: Are all FRBs repeating, or only some of them do?

Considering how early searches show no repetition, it is easy to dismiss the question in favor of saying that only some FRBs repeat.
However, it is important to note that there is no guarantee that the apparently non-repeating FRBs will not repeat.
It might be the case that the repetition of the apparently non-repeating FRBs have not been observed due to long repeating period [@bohanchen_uncloaking_2021].

By 2021, the CHIME/FRB Catalog 1^[<https://www.chime-frb.ca/catalog>] records 18 (3.7%) repeating sources out of 492 FRB sources [@the_chimefrbcollaboration_FirstCHIMEFRB_2021].
It is clear that only a small portion of the FRB population show repetition.
Multiple statistical analyses show consistent differences between repeating and non-repeating FRB in various properties [@cui_FastRadioBursts_2021; @chen_OneoffRepeatingFast_2022; @zhang_StatisticalSimilarityRepeating_2022].
These statistical significances support the idea that repeaters and non-repeaters may come from different populations of FRB.

### Predicting Repeatability {#sec-class-repeating-predict}

Classifying an FRB as repeating or non-repeating remains the only classification to this day.
This classification is still not definitive because as mentioned earlier, there is no guarantee that non-repeating FRB will not repeat.
Recent researchers such as @pleunis_FastRadioBurst_2021, @bohanchen_uncloaking_2021, @zhuge_machinelearningfrb_2022 and @luo_machinelearningfrb_2022 tried to predict which non-repeating FRB has the potential to repeat using differing strategies which will be described in the following subsections.

<!-- FRB 121102 is extensively studied among the known FRB with about 7% of the literature on "fast radio bursts" contains the keyword "FRB 121102" in its title or abstract up to the year 2022 as indexed by the NASA Astrophysics Data System^[<https://ui.adsabs.harvard.edu/>] illustrated in @fig-literature.
This particular FRB is special in several ways:

1. it is the first FRB detected outside of Parkes telescope [@spitler_FastRadioBurst_2014; @petroff_fast_2019], confirming it as an astronomical phenomenon.
2. it is the first FRB detected to be repeating.
3. it is also the only FRB to be detected actively repeating with at least 100 subbursts [@li_StatisticalPropertiesRepeating_2019b].

```{python}
#| fig-cap: The trends of papers with key words 'Fast Radio Burst' and 'FRB 121102' in its title or abstract as indexed by the NASA Astrophysics Data System (NASA/ADS)
#| label: fig-literature

import os

import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns; sns.set_theme()

DATAPATH = os.getenv('DATAPATH')

nasa_ads_frb = pd.read_csv(
    Path(DATAPATH, 'raw', 'external', 'NASA-ADS-FRB-all-papers-count.csv')
    )
nasa_ads_frb121102 = pd.read_csv(
    Path(DATAPATH, 'raw', 'external', 'NASA-ADS-FRB121102-papers-count.csv')
    )
nasa_ads_frb['Key word'] = 'Fast Radio Bursts'
nasa_ads_frb121102['Key word'] = 'FRB 121102'

data = pd.concat([nasa_ads_frb121102, nasa_ads_frb])
data['Items'] = data['Article Count'].apply(lambda x: ['x'] * x)
data = data.explode('Items')

plt.figure(figsize=(8,4))
ax = sns.histplot(data, x='Year', hue='Key word', bins=len(data['Year'].unique()), element='step', multiple='dodge')
sns.move_legend(ax, 'upper left')
```
-->

## Morphological Differences {#sec-class-morphology}

By examining the structure of these signals, @pleunis_FastRadioBurst_2021 found that FRBs can be divided into four different morphology archetypes.
They are: (i) broadband simple burst, (ii) narrowband simple burst, (iii) complex multi-peak, and (iv) complex multi-subburst.
The multi-peak archetype shows peaks at similar frequency ranges.
The complex multi-subburst archetype, however, show an apparent downwards shift in frequency with respect to time.


They found that repeaters never fall under archetype (i) but archetype (iv) was almost always seen in repeaters.
Moreover, the repeater subbursts never show an upwards shift in frequency.
Using this information, they try to deduce which of the non-repeaters might repeat based on their morphology. 
They expect the following FRBs to repeat: FRB 20181125A, FRB 20190308C, FRB 20190527A, FRB 20190422A, FRB 20190423A, FRB 20190601C.

![Single examples from the CHIME/FRB Catalog of the different FRB morphologies numbered according to their archetype number. These are FRBs 20190527C, 20190515D, and 20181117B and the 2019 August 10 burst of repeating FRB 20190117A [@pleunis_FastRadioBurst_2021].](../_common/figures/plenius-archetype.jpg){#fig-pleunis-archetype}

![The morphologies of some non-repeaters showing an apparent upward shift in frequency. [@pleunis_FastRadioBurst_2021]](../_common/figures/pleunis-non-repeater-upwards-shift.jpg){#fig-non-repeaters-upward-shift}

## Using Machine Learning {#sec-class-ml}

Machine learning is a set of task designed for a computer to draw more refined conclusions about a dataset so as to be able to make confident predictions about unseen data, usually by running an algorithm iteratively and self-tuning its hyperparameters.
Algorithms of machine learning are divided into two types: supervised and unsupervised learning [@vanderplas_PythonDataScience_2016].
A supervised learning is when the input data is labelled where the computer will try to predict the label of unseen data as the result of its training.
In contrast, an unsupervised learning is when the input data is unlabelled where the computer will try to predict the relationships between data features to uncover a pattern.

Inferring relationships directly from multi-dimensional features of FRBs is hard so some authors utilized a dimensional reduction algortihm where multi-dimensional features are reduced to a 2-dimensional projection space where the relative separation can be easily visualized. 
Furthermore by employing a clustering algorithm to a data of reduced dimension, one can reveal data points that belong to the same group.
These two algorithms belong to a class of unsupervised machine learning [@vanderplas_PythonDataScience_2016] because it doesn't require knowledge about which data belong to which label.

@bohanchen_uncloaking_2021 and @zhuge_machinelearningfrb_2022 uses this unsupervised machine learning workflow to reveal relationships between FRB.
Both papers found that FRBs with similar feature clump together.
Additionally, some non-repeaters are seen to clump together with repeaters even though the algorithm has no knowledge on whether it shows repetition or not.
It is reasonable to propose that these non-repeating FRBs have latent features of true repeaters and therefore have a potential to repeat [@bohanchen_uncloaking_2021].

![A 2D projection space for 13 features of FRBs using the _Uniform Manifold Approximation and Projection_ (UMAP) algorithm [@mcinnes_UMAP_2018]. Note that the x and y direction of a UMAP projection has no specific meaning. However, the algorithm prioritizes preserving the local structure of the data set therefore the formation of clumps means that they are related to each other. The grouping is identified using Hierarchical Density-Based Spatial Clustering of Applications with Noise (HDBSCAN) [@campello_HDBSCAN_2013]. The 13 features are (i) boxcar width, (ii) intrinsic width, (iii) peak flux, (iv) fluence, (v) scattering time, (vi) spectral index, (vii) spectral running, (viii) highest frequency, (ix) lowest frequency, (x) peak frequency, (xi) redshift, (xii) radio energy, and (xiii) rest-frame intrinsic duration. Parameters xi-xiii are model dependent.](../_common/figures/repeater-candidates_NC_Chen2022.jpg){#fig-repeater-candidates-Chen2022 width=50%}

Another class of machine learning algorithm is one where knowledge abut the data label is required in its prediction.
These are aptly named 'supervised machine learning' [@vanderplas_PythonDataScience_2016].
An example of which is used by @luo_machinelearningfrb_2022 to try to predict potentially repeating FRBs from among the non-repeaters using a classification algorithm.
By running the task multiple times in multiple implementation of this classification algorithm^[The implementation of a classification algorithm used in the paper includes decision tree method, random forest method, support vector machine method, and the nearest centroid method.], some FRBs are seen to be consistently predicted to be repeating.
Similarly, it is reasonable to propose that these FRBs have latent features of true repeaters and therefore have a potential to repeat.

<!-- TODO: Diagram the different workflow -->

### Feature Importance {#sec-class-ml-features}

One disadvantage of using machine learning as a prediction tool is that they are not based on nor do they produce any physical model which can be seen as a non-progress.
However, these prediction produces a list of features (FRB properties) that can be ranked based on importance.
The importance of a feature is defined by how much the result of a prediction changes when the selected feature is removed from the algorithm.
The frequency range and peak frequency of the FRB subburst is consistently ranked high in importance across all three studies [@bohanchen_uncloaking_2021; @luo_machinelearningfrb_2022; @zhuge_machinelearningfrb_2022].
The scattering time, fluence and flux are ranked high in @bohanchen_uncloaking_2021 while brightness temperature is ranked high in @luo_machinelearningfrb_2022.
For comparison, statistical differences have been found between repeaters and non-repeaters with regards to temporal pulse width [@cui_FastRadioBursts_2021; @chen_OneoffRepeatingFast_2022], dispersion measure [@zhang_StatisticalSimilarityRepeating_2022], and luminosity [@cui_FastRadioBursts_2021; @chen_OneoffRepeatingFast_2022].

## Star Formation History {#sec-class-history}

@guo_PossibleSubclassificationFast_2022 proposed an additional classification based on their association with a old (type a) or young (type b) stellar population.
They divide FRBs into four: Type Ia, Ib, IIa, and IIb; where type I and type II corresponds to non-repeating and repeating FRB respectively.
The idea that FRBs might track the star formation history of the universe was first tested in @zhang_CHIMEFastRadio_2022 and later in @qiang_FastRadioBurst_2022.
Both studies consistently reject the idea.

However, both studies do not differentiate between repeaters and non-repeaters.
The number of repeaters are too small for it to be meaningfully compared to the star formation history model on its own. 
@guo_PossibleSubclassificationFast_2022 attempted to create a subclassification of their own and argued that some FRBs might track star formation history while others do not.

They approached the problem by finding a critical value for separation of selected properties that produces the lowest p-value.
This results in 10 regions with 3 of them being a combined region as shown in @fig-transient-duration-vs-luminence_guo2022.
They found that FRBs outside region 8 track star formation history while FRBs inside region 8 do not. 

![The distribution of repeaters (red) and non-repeaters (blue) in the $\nu W-L_\nu$ phase space with the divided line. Regions are labelled as per the paper but added by author. Regions with parentheses marks a combined region [@guo_PossibleSubclassificationFast_2022].](../_common/figures/transient-duration-vs-luminence-labelled_guo2022.png){#fig-transient-duration-vs-luminence_guo2022 width=70%}

It it stressed by the author that their work is highly speculative.
A glance at @fig-transient-duration-vs-luminence_guo2022 reveals that there is no clear separation between regions.
Furthermore, the authors made a questionable decision by using used a very non-familiar property of FRB, which they call "Transient Duration" which seems to be a product of its frequency width $\nu$ and temporal width $W$.
This author discouraged their approach and will not be considered in this proposal. 

Future works where more classification is established might reveal that there are type a and type b FRBs.
However, the results obtained by @zhang_CHIMEFastRadio_2022 and @qiang_FastRadioBurst_2022 is much more supported in the current research landscape.
It is best to conclude that the current FRB population does not track star formation history.