:::{.content-visible unless-profile="litreview"}
## Instruments
One reason for the abundance of the detection of FRBs is that many telescope dedicated to FRB has been built within the last decade.
Listed here are several telescopes that have been known to provide open data for FRB transients:

### CHIME/FRB
The Canadian Hydrogen Intensity Mapping Experiment (CHIME) is a stationary radio telescope located in the southern parts of British Columbia, Canada (49^∘^ 19^'^ 14^''^.52 N,  119^∘^ 37^'^ 25^''^.25 W).
Unlike conventional dish shaped radio telescope, CHIME consists of four 20m x 100m semi-cylindrical reflectors pointed skywards to achieve 8000m^2^ area with a sensitivity between 400 to 800 MHz [@the_chimefrb_collaboration_chime_2018].
This allows the telescope to map ≳200 square degrees of the sky continuously with three different output pipelines: CHIME/Cosmology, CHIME/FRB, and CHIME/Pulsar.
The data relevant to this study is from the CHIME/FRB pipeline.

### Parkes
The Parkes radio telescope is a 64-meter steerable radio telescope located in the central-west region of New South Wales, Australia.
It was the telescope used by Lorimer for the serendipitous discovery of the FRB in @lorimer_bright_2007.
It has been given the name Murriyang in honour of Australian aboriginals in 2020.
However, the name “Parkes radio telescope” or “Parkes” remains in use within the literature.
:::