:::{.content-visible when-profile="proposal"}

## Research Objective {#sec-objective}

Given that nature of FRBs is currently unknown and many have proposed a progenitor theory, this research does not attempt to add a new progenitor theory into the literature.
This research proposes to find similarities and differences in the current population of detected FRBs.
This approach will help progress in constraining theories on FRB's origin and the search for FRB sources.

There is a possibility that FRBs may come from different origins masked as a single phenomena which adds complexity to this endeavour.
However, even if there is a possible subpopulation of FRBs, the differences between them are not obvious.
@Sec-classification summarizes the effort on classifying FRBs.
This study attempts to add a dimension to classification efforts by seriously considering morphological archetypes (@Sec-class-morphology) as a property of FRB.

This study aims to investigate the relationship between the morphology of FRBs with other properties described in @sec-properties.
Then, the effect of the morphology of FRBs to the statistical analysis and machine learning results will be investigated.
Finally, the results from this study and previous study with newly released data catalog (@Sec-method-data-new-repeaters) will be compared.

:::