# Properties {#sec-properties}

The properties of an FRB can be divided into two types: an observed property and a derived property.
An observed property is a property that is apparent from the signal whose value can be taken directly from the signal or calculated with minimal assumption.
A derived property is a property whose value highly depends on the model used for the calculation.

## Observed Properties

Given a single pulse of FRB, the following properties can be observed: frequency range, pulse width, fluence, flux, scattering time, spectral index.
Some of them are discussed in this section.

<!-- TODO Write -->
<!-- ## Frequency Ranges {#sec-prop-freq}

... -->

### Dispersion Measure {#sec-prop-dm}

As radio signals propagate through space, it interacts with mediums it encounters and thus is dispersed.
As a consequence, its arrival time is directly dependent on its frequency with lower frequencies arriving later [@day_pinpointing_2022; @kulkarni_dispersion_2020].
The measure of this dispersion – its dispersion measure (DM) – is a key observable quantity in studies of FRBs [@keane_fast_2016].
It is generally accepted that the DM of a FRB transient is due to free electrons encountered, $n_e$, along the path, $\text{d}l$, with the relation,
$$
\text{DM} = \int_0^d n_e \text{d}l.
$$ {#eq-DM-electron-density}

However, it is worth noting that ionized particles, plasma temperature, magnetic fields and its relative motion contribute to this measure even though these other contributions are very small and can be neglected [@kulkarni_dispersion_2020].

The DM of a given transient is calculated using two observables: its arrival time, $t$, and its frequency, $\nu$; where the DM is related by the slope relation
$$
\text{DM} = a\frac{\Delta t}{\Delta\nu^{-2}_{\text{lo}-\text{hi}}},
$$ {#eq-DM-slope-a}
or more directly
$$
\text{DM} = K\Delta t\Delta\nu^{-2}_{\text{lo}-\text{hi}},
$$ {#eq-DM-slope-k}
where $a=K^{-1}$ and $\Delta\nu^{-2}_{\text{lo}-\text{hi}}$ is the difference of the inverse square of highest and lowest frequency.
Users of calculation software should be made aware which conventions are used.
For the sake of precision, both values with its uncertainty are provided here [@kulkarni_dispersion_2020]:


$$
    a = 4.148 806 4239(11) \text{GHz}^2\text{pc}^{-1}\,\text{cm}^3\text{ms}
$${#eq-dm-coefficients-a}
$$
    K = 241.033 1786(66)  \text{GHz}^{-2}\text{pc}\,\text{cm}^{-3}\text{s}
$${#eq-dm-coefficients-k}

### Intrinsic Pulse Width

The observed temporal width is smeared by the dispersion of the signal and depends on the sampling time of the instrument. For that reason, we estimate a signal's intrinsic pulse width, $t_i$, using the formula [@cui_FastRadioBursts_2021; @connor_BeamingExplanationRepetition_2020],
$$
t_i = \sqrt{t_\text{obs}^2 - t_\text{sampling time}^2 - t_\text{dispersion}^2}
$${#eq-intrinsic-time-width}
where $t_\text{sampling time}$ is the sampling time of the telescope and $t_\text{dispersion}$ is the dispersion smearing given by,x
$$
t_\text{dispersion} = 8.3\times 10^{-3} \text{DM} \frac{\Delta_\text{bandwidth}\nu_\text{MHz}}{\nu^3_\text{GHz}} \text{(in ms)},
$${#eq-time-width-smearing}
where $\Delta_\text{bandwidth}\nu_\text{MHz}$ is the channel bandwidth and $\nu_\text{GHz}$ is the central frequency with their respective units in subscript.
It is important to note that some datasets have already given their FRB intrinsic width such as the column `width_fitb` in the CHIME/FRB Catalog [@the_chimefrbcollaboration_FirstCHIMEFRB_2021].

### Flux Density and Fluence

The fluence, $\mathcal{F}$, of a transient is the total energy received by the antenna throughout the duration of the signal typically measured in Jansky seconds, $\text{J}\cdot\text{s}$.
It is characterized by the expression [@petroff_fast_2019]
$$
\mathcal{F} = \int_\text{pulse} S(t) \text{d}t,
$$ {#eq-fluence-by-integral}
where $S(t)$ is the flux density of the signal. 
We can then characterize the peak flux density, $S_\text{peak}$ and its pulse width, $W_\text{pulse}$ like so:
$$
\mathcal{F} = S_\text{peak} W_\text{peak}.
$$ {#eq-fluence-by-peaks}

###	Rotation Measure
Analogous to dispersion measure, where the frequency is dispersed by the interacting medium, the radio wave may also be rotated as electrons interact with its magnetic field component.
This rotation is measurable via its polarization, $\Theta$, which is proportional to its wavelength squared, $\lambda^2$,
$$
\Theta = \text{RM} \lambda^2,
$$ {#eq-RM}
where RM is the Faraday rotation measure.
This quantity, RM, is analogous to @eq-DM-electron-density for DM as it is the total interaction along the line of sight [@brentjens_faraday_2005; @feng_frequency-dependent_2022],
$$
\text{RM} = -0.81\int_0^d B(l)_\parallel n_e(l) \text{d}l.
$$ {#eq-RM-intergral}

## Derived Properties

Most of the derived properties rely heavily on the cosmological models used.
Here, we can see that the redshift of an FRB rely on assumptions about the distribution of matter.
Other derived property rely on this redshift.
As we do not know the source of the FRB, we have no other way of corroborating its true distance.
This method remains the only method.   
<!-- ### Luminosity -->
<!-- TODO: Isi -->

### Redshift
The DM of the FRBs can be used to infer the distance of the source by estimating contributions along the line of sight.
FRBs typically have DM more than the contributions from Milky Way, $\text{DM}_\text{MW}$, suggesting that it is an extragalactic phenomenon.
Non-Milky Way contributions to the observed DM (its dispersion measure excess, $\text{DM}_\text{E}$) come from the intergalactic medium (IGM) and the host galaxy [@deng_cosmological_2014; @petroff_fast_2019],
$$
\text{DM}_\text{E} = \text{DM}-\text{DM}_\text{MW} =\text{DM}_\text{IGM} + \left(\frac{\text{DM}_\text{Host}}{1+z}\right),
$$ {#eq-DM-excess}
where $z$ is the redshift associated with the host galaxy. 
The $\text{DM}_\text{Host}$ of the transient depends its distance from the host galactic core and viewing angle [@thornton_population_2013] because those factor determines how much material interacts with the signal throughout its propagation.
It is usually assumed to be $50.0\,\text{pc}\,\text{cm}^{-3}$ [@shannon_DispersionBrightnessRelation_2018; @hashimoto_LuminosityDurationRelation_2019; @arcus_FastRadioBurst_2021] with minimal effect given that the observed DM is large[@arcus_FastRadioBurst_2021].

Some studies differentiate between the DM contribution of the Milky Way disc, $\text{DM}_\text{MW, disc}$, and the Milky Way halo, $\text{DM}_\text{halo}$ where $\text{DM}_\text{MW} = \text{DM}_\text{MW, disc} + \text{DM}_\text{halo}$.
The Milky Way disc contribution can be calculated using an electron density model (EDM) associated with @eq-DM-electron-density up to 10 kpc while the halo contribution is estimated between 50~80 pc cm^-3^ (reported in @prochaska_ProbingGalacticHaloes_2019a and quoted by @hashimoto_NoRedshiftEvolution_2020 and @hashimoto_LuminosityDurationRelation_2019).
Two EDMs often quoted in the FRB literature is the NE2001 [@cordes_NE2001NewModel_2002] and the YMW16 [@yao_NewElectronDensityModel_2017].
Its value highly depends on its galactic latitude as there is little material higher up in the latitude so its DM is expected to be small [@thornton_population_2013].

The redshift of FRB can be calculated by the $\text{DM}_\text{IGM}$ [@hashimoto_NoRedshiftEvolution_2020],
$$
\text{DM}_\text{IGM}(z) = \Omega_b \frac{3H_0c}{8\pi G m_p}
    \times \int_0^z \frac{(1 + z^\prime) f_\text{IGM}(z^\prime) (Y_H X_{e,H}(z^\prime) + \frac{1}{2}Y_p X_{e,He}(z^\prime))}{\{\Omega_m (1 + z^\prime)^3 + \Omega_\Lambda(1 + z^\prime)^{3[1+w(z^\prime)]}\}1/2} dz^\prime,
$$
assuming a flat universe. 
$X_{e,}$ and $Y$ are the ionization fractions and mass fractions of the intergalatic hydrogen (H) and helium (He) accordingly.
$f_\text{IGM}$ is the fraction of baryons in the IGM.

<!-- TODO: Isi
### Luminosity Distance

$D_L(z) = (1+z) D_M$ (line of sight co-moving distance) TODO: Rujuk @macquart_FRBEventRate_2018

TODO: Isi

### Brightness Temperature

TODO: Isi  -->


### Energy

The energy of a FRB can be calculated as a time-integration of its luminosity function at rest frame $\nu_\text{rest}$ GHz [@hashimoto_LuminosityDurationRelation_2019],

$$
    E_{\nu_\text{rest}} = \int_\text{pulse} \frac{4\pi D_L(z)^2}{(1+z)^{1+\alpha}}\left(\frac{\nu_\text{rest}}{\nu_\text{obs}}\right)^\alpha S_{\nu_\text{obs}} \text{d}t
$${#eq-energy-by-time-integrated-luminosity-int}
$$
    E_{\nu_\text{rest}} = \frac{4\pi D_L(z)^2}{(1+z)^{2+\alpha}}\left(\frac{\nu_\text{rest}}{\nu_\text{obs}}\right)^\alpha\mathcal{F}_{\nu_\text{obs}} \text{(in ergs Hz$^{-1}$)}
$${#eq-energy-by-time-integrated-luminosity-eval}

where $D_L(z)$ is the luminosity distance calculated from redshift and -- following @eq-fluence-by-integral -- $S{_{\nu_\text{obs}}}$ is the flux density at the observed frequency and $\mathcal{F}{_{\nu_\text{obs}}}$ is its fluence.
However, @hashimoto_EnergyFunctionsFast_2022 offered an energy function derived directly from a fluence integreated over frequency because the fluence is less affected by the finite time resolution of instruments [@macquart_FRBEventRate_2018] and it minimizes uncertainty over diverse spectral shapes highlighted in @pleunis_FastRadioBurst_2021. It is calculated as
$$
E_\text{obs} = \mathcal{F}_\text{obs} \times 400\text{MHz}.
$${#eq-energy-obs-400}
This formula corresponds different frequency widths at different redshifts. 
To correct for the effect of redshift, we use the integration over 400MHz at rest-frame, $\Delta\nu_{\text{obs, itg}} = \frac{400}{(1+z)} MHz$.
Now the observed energy at rest-frame 400 MHz is approximated as follows,
$$
E_\text{obs, 400} = 
\begin{cases}
\mathcal{F_\text{obs}} \times 400 \text{MHz},& \text{if} \Delta\nu_\text{obs, itg} \geq \Delta\nu_\text{obs, FRB}\\
\mathcal{F_\text{obs}} \times 400 \text{MHz} (\frac{\Delta\nu_\text{obs,itg}}{\Delta\nu_\text{obs, FRB}}),& \text{if} \Delta\nu_\text{obs, itg} < \Delta\nu_\text{obs, FRB}.
\end{cases}
$${#eq-energy-obs-400-z-corrected}
Then, the rest-frame isotropic radio energy ($E_\text{rest, 400}$) is given by [@hashimoto_EnergyFunctionsFast_2022],
$$
E_\text{rest, 400} = \frac{4\pi D_L(z)^2 E_\text{obs, 400}}{(1+z)}\, \text{(in ergs)}.
$$