project:
  type: website
  preview: 
      port: 4050
  render: 
      - 'index.qmd'
      - notebooks/*
      - 'README.md'

website:
  title: "Masters Project"
  navbar:
    right:
      - README.md
  #     - icon: github
  #       href: https://github.com/
  #     - icon: twitter
  #       href: https://twitter.com
format:
  html:
    theme: cosmo
    # css: styles.css
    twitter-card: true
    open-graph: true
    reader-mode: true

title-block-banner: true




