[tool.poetry]
name = "sarjana-muda"
version = "0.1.1"
description = ""
authors = ["Thaza_Kun <61819672+Thaza-Kun@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
requests = "^2.28.1"
asyncio = "^3.4.3"
pandas = "^1.5.0"
matplotlib = "^3.6.0"
mw-plot = "^0.9.0"
cfod = "^2021.6.4"
umap-learn = {extras = ["plot"], version = "^0.5.3"}
seaborn = "^0.12.1"

[tool.poetry.dev-dependencies]
ipykernel = "^6.15.3"

[tool.poetry.group.dev.dependencies]
nbformat = "^5.7.0"
ipywidgets = "^8.0.2"
plotly = "^5.10.0"
nbclient = "^0.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
