[tool.poetry]
name = "sarjana-muda"
version = "0.1.0"
description = ""
authors = ["Thaza_Kun <61819672+Thaza-Kun@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.28.1"
asyncio = "^3.4.3"
pandas = "^1.5.0"
matplotlib = "^3.6.0"
mw-plot = "^0.9.0"

[tool.poetry.dev-dependencies]
ipykernel = "^6.15.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
