<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Periodictity of FRB Repeaters with Limited Sample</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="repeaters_files/libs/clipboard/clipboard.min.js"></script>
<script src="repeaters_files/libs/quarto-html/quarto.js"></script>
<script src="repeaters_files/libs/quarto-html/popper.min.js"></script>
<script src="repeaters_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="repeaters_files/libs/quarto-html/anchor.min.js"></script>
<link href="repeaters_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="repeaters_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="repeaters_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="repeaters_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="repeaters_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="repeaters.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Periodictity of FRB Repeaters with Limited Sample</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Murthadza Aznam </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Universiti Malaya
          </p>
      </div>
      <div class="quarto-title-meta-contents">
    <p class="author">Zamri Zainal Abidin </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Universiti Malaya
          </p>
      </div>
      <div class="quarto-title-meta-contents">
    <p class="author">Norsiah Hashim </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Universiti Malaya
          </p>
      </div>
      <div class="quarto-title-meta-contents">
    <p class="author">Muhammad Hassan Zakie Yussoff </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Universiti Malaya
          </p>
      </div>
      <div class="quarto-title-meta-contents">
    <p class="author">Matdhesh Kummar Jayaganthan </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Universiti Malaya
          </p>
      </div>
    </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  

</header>

<!-- 
# Considerations
- [ ] Waiting time distribution
- [ ] Evolution
  - [ ] Morphology (Sigma or Tau)
  - [ ] Flux
  - [ ] Width
  - [ ] Energy

# Subjects
- [ ] Known Repeaters
  - [ ] FRB20180916B
- [ ] New Repeaters 
  - [ ] New repeater with more detections (FRB20201130A?)
  - [ ] FRB20190915D (Good example) 10 detections
  - [ ] FRB20191106C (Bad example) 7 detections
- [ ] Known repeaters with limited samples
  - [ ] FRB20180916B with
    - [ ] 0.25*Period window
    - [ ] 0.5*Period window
    - [ ] 1*Period window
    - [ ] 2*Period window
    - [ ] 3*Period window
-->
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Fast Radio Bursts (FRB) are a class of transients first discovered by <span class="citation" data-cites="lorimer_BrightMillisecondRadio_2007">Lorimer et al. (<a href="#ref-lorimer_BrightMillisecondRadio_2007" role="doc-biblioref">2007</a>)</span> with currently unknown origin. It is characterized as a radio pulse with durations in the order of milliseconds and a relatively high dispersion measure. Its high dispersion measure suggests an extragalactic origin consistent with observation of identified hosts such as <span class="citation" data-cites="bannister_SingleFastRadio_2019">Bannister et al. (<a href="#ref-bannister_SingleFastRadio_2019" role="doc-biblioref">2019</a>)</span>, <span class="citation" data-cites="chatterjee_DirectLocalizationFast_2017">Chatterjee et al. (<a href="#ref-chatterjee_DirectLocalizationFast_2017" role="doc-biblioref">2017</a>)</span>, and <span class="citation" data-cites="ravi_FastRadioBurst_2019">Ravi et al. (<a href="#ref-ravi_FastRadioBurst_2019" role="doc-biblioref">2019</a>)</span>.</p>
<p>With increasing interests in FRBs, progress have been made in detections (especially with the commisioning of the CHIME/FRB telescope <span class="citation" data-cites="thechimefrbcollaborationCHIMEFastRadio2018">(<a href="#ref-thechimefrbcollaborationCHIMEFastRadio2018" role="doc-biblioref">The CHIME/FRB Collaboration et al. 2018</a>)</span> and in the future, BURSTT <span class="citation" data-cites="lin_BURSTTBustlingUniverse_2022">(<a href="#ref-lin_BURSTTBustlingUniverse_2022" role="doc-biblioref">Lin et al. 2022</a>)</span>), theoretical models (a list of theories can be found in <span class="citation" data-cites="platts_LivingTheoryCatalogue_2019">Platts et al. (<a href="#ref-platts_LivingTheoryCatalogue_2019" role="doc-biblioref">2019</a>)</span>), and analyses (especially on regularly repeating bursts such as FRB20121102A and FRB20180916B). For an in-depth review of the growth of FRB research, readers are suggested to read <span class="citation" data-cites="petroff_FastRadioBursts_2019">Petroff, Hessels, and Lorimer (<a href="#ref-petroff_FastRadioBursts_2019" role="doc-biblioref">2019</a>)</span> and their follow-up review <span class="citation" data-cites="petroff_FastRadioBursts_2022">Petroff, Hessels, and Lorimer (<a href="#ref-petroff_FastRadioBursts_2022" role="doc-biblioref">2022</a>)</span>.</p>
<p>Currently, FRBs can be categorized as repeating or non-repeating. The population seem to favor non-repeating FRBs over repeating FRBs as <span class="citation" data-cites="thechimefrbcollaborationCHIMEFastRadio2018">The CHIME/FRB Collaboration et al. (<a href="#ref-thechimefrbcollaborationCHIMEFastRadio2018" role="doc-biblioref">2018</a>)</span> reports on 18 (3.7%) repeating sources are among 492 FRB sources detected<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. However, it is important to note that there is no guarantee that one-off FRBs will not repeat. Following this assumption, the term ‘apparently non-repeating FRB’ have been used in various papers, such as in <span class="citation" data-cites="cui_FastRadioBursts_2021">Cui, Zhang, Wang, Zhang, Li, Peng, Zhu, Wang, et al. (<a href="#ref-cui_FastRadioBursts_2021" role="doc-biblioref">2021</a>)</span>, <span class="citation" data-cites="cui_StatisticalPropertiesFast_2021">Cui, Zhang, Wang, Zhang, Li, Peng, Zhu, Strom, et al. (<a href="#ref-cui_StatisticalPropertiesFast_2021" role="doc-biblioref">2021</a>)</span>, and <span class="citation" data-cites="katz_AbsencePeriodicityRepeating_2022">Katz (<a href="#ref-katz_AbsencePeriodicityRepeating_2022" role="doc-biblioref">2022</a>)</span>. Multiple statistical analyses seem to support the idea that they are truly two different population of FRBs with consistent differences between repeating and non-repeating FRB in various properties <span class="citation" data-cites="cui_FastRadioBursts_2021 chen_OneoffRepeatingFast_2022 zhang_StatisticalSimilarityRepeating_2022">(<a href="#ref-cui_FastRadioBursts_2021" role="doc-biblioref">Cui, Zhang, Wang, Zhang, Li, Peng, Zhu, Wang, et al. 2021</a>; <a href="#ref-chen_OneoffRepeatingFast_2022" role="doc-biblioref">Chen et al. 2022</a>; <a href="#ref-zhang_StatisticalSimilarityRepeating_2022" role="doc-biblioref">Zhang et al. 2022</a>)</span>. This consistency does not prevent some authors in assuming that a small part of the non-repeating FRBs might repeat in the future, as was done by <span class="citation" data-cites="bohanchen_UncloakingHiddenRepeating_2021">Bo Han Chen et al. (<a href="#ref-bohanchen_UncloakingHiddenRepeating_2021" role="doc-biblioref">2021</a>)</span>, <span class="citation" data-cites="luo_MachineLearningClassification_2022">Luo, Zhu-Ge, and Zhang (<a href="#ref-luo_MachineLearningClassification_2022" role="doc-biblioref">2022</a>)</span>, <span class="citation" data-cites="zhu-ge_MachineLearningClassification_2022">Zhu-Ge, Luo, and Zhang (<a href="#ref-zhu-ge_MachineLearningClassification_2022" role="doc-biblioref">2022</a>)</span>, and <span class="citation" data-cites="pleunis_FastRadioBurst_2021">Pleunis et al. (<a href="#ref-pleunis_FastRadioBurst_2021" role="doc-biblioref">2021</a>)</span>.</p>
<p>Regularly repeating FRBs such as FRB20121102A and FRB20180916B are rare. Most of the repeaters currently identified has a limited sample which makes it hard to study its individual property. As such, many repeaters are understudied as its low number of samples provide limited certainty. This paper tries to study the property of individual sources with limited samples.</p>
<p>Since periodicity generally requires many data points, this paper examines whether it is possible to determine the periodicity of a source with at least 50% confidence using samples with more than 3 and less than 20 event counts? If so, what are the criteria to differentiate between determinable and non-determinable periodicity? Having this criteria can help anticipate new detections.</p>
</section>
<section id="methodology" class="level1">
<h1>Methodology</h1>
<!-- TODO Confirm event counts -->
<p>This paper will examine the periodicity of FRB20190915D (13 detections) and FRB20191106C (7 detections) from the CHIME/FRB Catalog 2023<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> <span class="citation" data-cites="andersen_CHIMEFRBDiscovery_2023">(<a href="#ref-andersen_CHIMEFRBDiscovery_2023" role="doc-biblioref">Andersen et al. 2023</a>)</span>. This paper will also include FRB20180916B (? detections) from CHIME/FRB Catalog 1<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> <span class="citation" data-cites="thechimefrbcollaborationFirstCHIMEFRB2021">(<a href="#ref-thechimefrbcollaborationFirstCHIMEFRB2021" role="doc-biblioref">The CHIME/FRB Collaboration et al. 2021</a>)</span> to compare the validity of methods since its periodicity value is well quantified to be around 16 days <span class="citation" data-cites="thechimefrbcollaborationPeriodicActivityFast2020 sand_CHIMEFRBStudy_2023">(<a href="#ref-thechimefrbcollaborationPeriodicActivityFast2020" role="doc-biblioref">The CHIME/FRB Collaboration et al. 2020</a>; <a href="#ref-sand_CHIMEFRBStudy_2023" role="doc-biblioref">Sand et al. 2023</a>)</span>.</p>
<section id="periodogram" class="level2">
<h2 class="anchored" data-anchor-id="periodogram">Periodogram</h2>
<p>A periodogram is a function of cost versus periods which quantifies the strength of the fit between the given period and the time series data. The cost function depends on the method of choice. The best period is chosen based on the period with the maximum or minimum cost. While most periodogram methods choose the best period via the maximum cost, the phase dispersion minimization method chooses the minimum cost. <span class="citation" data-cites="vanderplas_UnderstandingLombScargle_2018">VanderPlas (<a href="#ref-vanderplas_UnderstandingLombScargle_2018" role="doc-biblioref">2018</a>)</span> includes four types of periodograms: (1) Fourier Method, based on Fourier transforms; (2) Phase-Folding Method, which calculates cost by trying to fold phases at multiple trial periods; (3) Least-Square Method, which fits a model time series; and (4) Bayesian Approaches, which applies Bayesian probability to the problem.</p>
<section id="method-lombscargle-periodogram" class="level3">
<h3 class="anchored" data-anchor-id="method-lombscargle-periodogram">Method: Lomb–Scargle Periodogram</h3>
<p>The Lomb–Scargle periodogram <span class="citation" data-cites="lomb_LeastSquaresFrequencyAnalysis_1976">Scargle (<a href="#ref-scargle_StudiesAstronomicalTime_1982" role="doc-biblioref">1982</a>)</span> is the most commonly used in astronomy. The cost function for this periodogram is the Fourier power which is to be maximized. As such, it is a periodogram based on Fourier transform but it can also be approached as a least square optimization <span class="citation" data-cites="vanderplas_UnderstandingLombScargle_2018">(<a href="#ref-vanderplas_UnderstandingLombScargle_2018" role="doc-biblioref">VanderPlas 2018</a>)</span>. The widespread use of this method warrants its place in the <code>astropy</code> package<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>, an astronomy package for the Python programming language.</p>
</section>
<section id="method-duty-cycle" class="level3">
<h3 class="anchored" data-anchor-id="method-duty-cycle">Method: Duty Cycle</h3>
<p>The Duty Cycle method is a phase–folding periodogram which measures the trial period with the longest continuous inactivity per cycle of a given FRB. This method was introduced by <span class="citation" data-cites="rajwade_PossiblePeriodicActivity_2020">Rajwade et al. (<a href="#ref-rajwade_PossiblePeriodicActivity_2020" role="doc-biblioref">2020</a>)</span> to measure the periodicity of FRB20121102A because of the nature of repeaters to be active within a certain period per cycle. A duty cycle of 56% means that there is a continuous inactivity for 44% of the cycle.</p>
</section>
<section id="method-phase-dispersion-minimization" class="level3">
<h3 class="anchored" data-anchor-id="method-phase-dispersion-minimization">Method: Phase Dispersion Minimization</h3>
<p>Phase Dispersion Minimization (PDM) is a phase–folding method to determine the periodicity of non–sinusoidal time variation introduced by <span class="citation" data-cites="stellingwerf_PeriodDeterminationUsing_1978">Stellingwerf (<a href="#ref-stellingwerf_PeriodDeterminationUsing_1978" role="doc-biblioref">1978</a>)</span>. This method computes the variances, <code>theta</code>, of the data with respect to mean light curve at each trial periods and minimizes it. It is suitable for small dataset with irregularly sampled observations, such as the repeaters sampled in the CHIME/FRB 2023 Catalog. This paper will use the Python wrapper of this algorithm written in C using the <code>py-pdm</code><a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> package.</p>
</section>
<section id="parameter-frequency-grid" class="level3">
<h3 class="anchored" data-anchor-id="parameter-frequency-grid">Parameter: Frequency Grid</h3>
<p>For this study, we chose a frequency grid of <span class="math inline">\(f_\text{max}\)</span> = (3 days)<sup>-1</sup> to <span class="math inline">\(f_\text{min} = 0.5 * ( T_\text{obs}\, \text{days})^{-1}\)</span>, where <span class="math inline">\(T_\text{obs}\)</span> is the length of observation (1,007 days). The maximum frequency is chosen such that if the period of FRBs is less than 3 days, we would see it much more often at a daily or bidaily rate. On the other hand, the minimum frequency is chosen such that to minimize the windowing effect near the length of observation. Following the advice of <span class="citation" data-cites="vanderplas_UnderstandingLombScargle_2018">VanderPlas (<a href="#ref-vanderplas_UnderstandingLombScargle_2018" role="doc-biblioref">2018</a>)</span>, the frequency grid is chosen such that <span class="math inline">\(N_\text{eval}=n_0T_\text{obs}f_\text{max}\)</span> where <span class="math inline">\(n_0\)</span> is chosen to be 7.</p>
</section>
</section>
<section id="uncertainty-estimation" class="level2">
<h2 class="anchored" data-anchor-id="uncertainty-estimation">Uncertainty Estimation</h2>
<p>Periodograms do not usually have an associated uncertainty, especially non-Bayesian periodograms. As such, the Lomb–Scargle periodogram is equipped with a False Alarm Probability (FAP) associated at each power level to avoid false positives. However, the same cannot be said about other periodograms. It is treated with a case by case basis. For example, <span class="citation" data-cites="rajwade_PossiblePeriodicActivity_2020">Rajwade et al. (<a href="#ref-rajwade_PossiblePeriodicActivity_2020" role="doc-biblioref">2020</a>)</span> approached the problem by calculating the full width at half maximum of the peak.</p>
<p>This paper will try to estimate uncertainty by employing the leave-one-out strategy. For each event, <span class="math inline">\(k\)</span> detections of said event are used to find the best period for the chosen periodogram method. Then, <span class="math inline">\(k\)</span> samples of <span class="math inline">\(k-1\)</span> detections are run through the same method and twice the standard deviation of best periods between these <span class="math inline">\(k-1\)</span> detections are used as the uncertainty. The idea is that the uncertainty in the periodicity is tied to the fact that some observation might be missed.</p>
</section>
</section>
<section id="result" class="level1">
<h1>Result</h1>
<div id="fig-periodogram" class="quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;">
<p><img src="./img/FRB20180916B-periodogram-LS.png" class="img-fluid figure-img" style="width:30.0%"> <img src="./img/FRB20190915D-periodogram-LS.png" class="img-fluid figure-img" style="width:30.0%"> <img src="./img/FRB20191106C-periodogram-LS.png" class="img-fluid figure-img" style="width:30.0%"> <img src="./img/FRB20180916B-periodogram-PF.png" class="img-fluid figure-img" style="width:30.0%"> <img src="./img/FRB20190915D-periodogram-PF.png" class="img-fluid figure-img" style="width:30.0%"> <img src="./img/FRB20191106C-periodogram-PF.png" class="img-fluid figure-img" style="width:30.0%"> <img src="./img/FRB20180916B-periodogram-PDM.png" class="img-fluid figure-img" style="width:30.0%"> <img src="./img/FRB20190915D-periodogram-PDM.png" class="img-fluid figure-img" style="width:30.0%"> <img src="./img/FRB20191106C-periodogram-PDM.png" class="img-fluid figure-img" style="width:30.0%"></p>
</div>
</div>
<p></p><figcaption class="figure-caption">Figure&nbsp;1: The periodograms of FRB20180916B (left), FRB20190915D (middle column) and FRB20191106C (right) using Lomb–Scargle method (top), Duty Cycle method (middle row) and Phase Dispersion Minimization (bottom).</figcaption><p></p>
</figure>
</div>
<div id="tbl-result" class="anchored">
<table class="table">
<caption>Table&nbsp;1: The periods obtained from the specified methods in days and its uncertainty. The percentage in brackets for the ‘Duty Cycle’ column is the active fraction of the cycle.</caption>
<colgroup>
<col style="width: 21%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">burst name</th>
<th style="text-align: center;">Lomb–Scargle</th>
<th style="text-align: center;">Duty Cycle</th>
<th style="text-align: center;">Phase Dispersion Minimization</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">FRB20180916B</td>
<td style="text-align: center;">16.33±0.00</td>
<td style="text-align: center;">16.30±0.21 (36.8%)</td>
<td style="text-align: center;">23.56±0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">FRB20190915D</td>
<td style="text-align: center;">30.06±10.21</td>
<td style="text-align: center;">29.97±0.95 (10.5%)</td>
<td style="text-align: center;">47.75±0.14</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FRB20191106C</td>
<td style="text-align: center;">3.16±8.80</td>
<td style="text-align: center;">3.87±20.81 (26.3%)</td>
<td style="text-align: center;">71.86±234.36</td>
</tr>
</tbody>
</table>
</div>
<p>The results shown in <a href="#tbl-result">Table&nbsp;1</a> accompanied by <a href="#fig-periodogram">Figure&nbsp;1</a> for FRB20180916B using Lomb–Scargle and Duty Cycle methods are consistent with the periodicities from <span class="citation" data-cites="thechimefrbcollaborationPeriodicActivityFast2020">The CHIME/FRB Collaboration et al. (<a href="#ref-thechimefrbcollaborationPeriodicActivityFast2020" role="doc-biblioref">2020</a>)</span> of 16.35±0.15 days and <span class="citation" data-cites="sand_CHIMEFRBStudy_2023">Sand et al. (<a href="#ref-sand_CHIMEFRBStudy_2023" role="doc-biblioref">2023</a>)</span> of 16.34±0.07 days. This consistency indicates that the methodology is reliable in determining periodicity using the available data. The Phase Dispersion Minimization method, however, offshoots by about ~1.4 times the obtained periodicity from the previous two methods.</p>
<p>This pattern also emerges in the results for FRB20190915D with Lomb–Scargle and Duty Cycle methods showing a periodicity of 30.06±10.21 days and 29.97±0.95 days respectively, with Phase Dispersion Minimization offshooting to 1.5~1.6 times the two values. This hints that these values might point to the real periodicity of the newly discovered FRB20190915D even though the available data is limited. The Phase Dispersion Minimization seems to consistently obtain 1.5 period days which is somewhat like a harmonic, equivalent to the second harmonic equivalent to <span class="math inline">\(1.5\times \lambda\)</span> standing wave.</p>
<p>The same could not be said for FRB20191106C for two reasons. First, although it has consistent values for the first two methods, the Phase Dispersion Minimzation period is 18.5~22.7 times the previous two values. This does not follow the pattern of the previous FRBs. Secondly, we have to be careful in interpreting periodogram values. While it is true that the first two values are consistent, it is imperative to understand that 3 days is the minimum period chosen for this analysis and periodograms tend to spike at high frequency limit, which explains the high uncertainty.</p>
<div id="fig-fold" class="quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-fold-FRB20180916B" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="./FRB20180916B-phase-16.33.png" class="img-fluid figure-img" data-ref-parent="fig-fold"></p>
<figcaption class="figure-caption">(a) FRB20180916B at 16.33 days</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-fold-FRB20190915D" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="./FRB20190915D-phase-30.06.png" class="img-fluid figure-img" data-ref-parent="fig-fold"></p>
<figcaption class="figure-caption">(b) FRB20190915D at 30.06 days</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 33.3%;justify-content: center;">
<div id="fig-fold-FRB20191106C" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="./FRB20191106C-phase-3.16.png" class="img-fluid figure-img" data-ref-parent="fig-fold"></p>
<figcaption class="figure-caption">(c) FRB20191106C at 3.16 days</figcaption>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figure&nbsp;2: Phase folded detection count of FRB at their selected periods.</figcaption><p></p>
</figure>
</div>
<!-- TODO Relate to the phase folding graph -->
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<section id="false-alarm-probability" class="level2">
<h2 class="anchored" data-anchor-id="false-alarm-probability">False Alarm Probability</h2>
<p>It is useful to quantify the false alarm probability (FAP) as a proxy of confidence. The FAP is computed using the ‘bootstrap’ method implemented in astropy’s <code>LombScargle</code> class. It is found that each FRBs has a FAP of 13.3% (FRB20180916B), 57.0% (FRB20190915D) and 66.0% (FRB20191106C). These values are consistent with the heuristics in the preceding paragraphs that the value for FRB20180916B has a higher confidence than for FRB20190915D while values obtained for FRB20191106C has the least confidence. The fact that the FAP for FRB20190915D is slightly above 50% but not any higher might be due to the fact that its detection only happens in a small time frame compared to the observation window. Fixing the window to be between 20 Jun 2019 and 15 May 2020 reduces the FAP to 44.2% – suggesting that there is more than 50% confidence that it has a periodicity if treated as a time-limited event. Further discussion on this property is in <a href="#sec-why-30">Section&nbsp;4.3</a>.</p>
</section>
<section id="waiting-time-distribution" class="level2">
<h2 class="anchored" data-anchor-id="waiting-time-distribution">Waiting time distribution</h2>
<p>One might wonder what distinguishes FRB20190915D from FRB20191106C which allowed one to have periodicity despite limited samples? Looking at the waiting time distribution in <a href="#fig-waitingtime">Figure&nbsp;3</a>, FRB20190915D clearly shows bimodal distribution consistent with FRB20180916B (shown here<!--TODO "and in" Citation needed -->) and FRB20121102A (shown in <span class="citation" data-cites="hewitt_AreciboObservationsBurst_2022">Hewitt et al. (<a href="#ref-hewitt_AreciboObservationsBurst_2022" role="doc-biblioref">2022</a>)</span> and <span class="citation" data-cites="jahns_FRB20121102ANovember_2022">Jahns et al. (<a href="#ref-jahns_FRB20121102ANovember_2022" role="doc-biblioref">2022</a>)</span>). Additionally, the waiting time of FRB20191106C is concentrated in the longer timescale compared to the bimodal distribution. It seems that a bimodal distribution is required for an FRB to have a well-defined periodicity.</p>
<div id="fig-waitingtime" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="./img/waiting.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;3: The waiting time distribution of FRB20191106C, FRB20191106C, and FRB20190916B in the <span class="math inline">\(\log_{10}\)</span> scale.</figcaption>
</figure>
</div>
</section>
<section id="sec-why-30" class="level2">
<h2 class="anchored" data-anchor-id="sec-why-30">Where is the rest of the detections?</h2>
<p>If it is indeed that FRB20190915D has a 30 day periodicity, why is there no additional detections within the 3 year window of the catalogue? It might be the case that this FRB has a multi-term periodicity with this value representing it’s short-term periodicity. If that is the case, it’s long-term periodicity is expected to be more than 2 years which is yet to be seen. However, this is the same as hypothesizing that repeaters are possible repeaters with not-yet-observed repetition.</p>
<p>Another hypothesis that might explain this seemingly lack of regular detection is that FRB20190915D is a cataclysmic event with a periodic pulse and stopping at a certain point, such as the inspiraling of two magnetic bodies whose interaction releases some radio bursts. This might explain the ever increasing detection count as it reaches peak and then no longer bursting.</p>
<div id="fig-FRB20190915D-countplot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="./img/FRB20190915D-countplot.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;4: The number of detections per day of FRB20190915D between 20th Jun 2019 between 15th May 2020. The gray coloured regions indicate the active fractions (10%) in a 30 day cycle from 25th Jul 2018. Note that this graph focuses on this small timeframe because the datasets spans from 25th Jul 2018 to 26th Apr 2021 but is empty throughout the beginning and end for the specified FRB.</figcaption>
</figure>
</div>
<!-- TODO Simulate cataclysmic event IF Possible (Periodicity with increasing counts per day and then nothing at all) -->
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>This paper determines that it is possible to evaluate the periodicity of FRBs despite small event counts. The bimodal distribution of waiting times seems crucial in the determinability of its periodicity. This paper also hints that there might a new class of FRB whose repeatability seems limited, suggesting that FRBs might be divided into three classes: (i) continuously repeating, (ii) limited repeating, or (iii) one-off.</p>
</section>
<section id="acknowledgement" class="level1">
<h1>Acknowledgement</h1>
<!-- TODO: Acknowledge geran VGOS 'for funding the the radio cosmology lab research activities' -->
</section>
<section id="references" class="level1 unnumbered">


</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-andersen_CHIMEFRBDiscovery_2023" class="csl-entry" role="listitem">
Andersen, B. C., K. Bandura, M. Bhardwaj, P. J. Boyle, C. Brar, T. Cassanelli, S. Chatterjee, et al. 2023. <span>“<span>CHIME</span>/<span>FRB Discovery</span> of 25 <span>Repeating Fast Radio Burst Sources</span>.”</span> <em>The Astrophysical Journal</em> 947 (January): 83. <a href="https://doi.org/10.3847/1538-4357/acc6c1">https://doi.org/10.3847/1538-4357/acc6c1</a>.
</div>
<div id="ref-bannister_SingleFastRadio_2019" class="csl-entry" role="listitem">
Bannister, K. W., A. T. Deller, C. Phillips, J. -P. Macquart, J. X. Prochaska, N. Tejos, S. D. Ryder, et al. 2019. <span>“A Single Fast Radio Burst Localized to a Massive Galaxy at Cosmological Distance.”</span> <em>Science</em> 365 (August): 565–70. <a href="https://doi.org/10.1126/science.aaw5903">https://doi.org/10.1126/science.aaw5903</a>.
</div>
<div id="ref-bohanchen_UncloakingHiddenRepeating_2021" class="csl-entry" role="listitem">
Bo Han Chen, Tetsuya Hashimoto, Tomotsugu Goto, Seong Jin Kim, Daryl Joe D. Santos, Alvina Y. L. On, Ting-Yi Lu, and Tiger Y. -Y. Hsiao. 2021. <span>“Uncloaking Hidden Repeating Fast Radio Bursts with Unsupervised Machine Learning.”</span> <em>Monthly Notices of the Royal Astronomical Society</em> 509 (1): 1227–36. <a href="https://doi.org/10.1093/mnras/stab2994">https://doi.org/10.1093/mnras/stab2994</a>.
</div>
<div id="ref-chatterjee_DirectLocalizationFast_2017" class="csl-entry" role="listitem">
Chatterjee, S., C. J. Law, R. S. Wharton, S. Burke-Spolaor, J. W. T. Hessels, G. C. Bower, J. M. Cordes, et al. 2017. <span>“A Direct Localization of a Fast Radio Burst and Its Host.”</span> <em>Nature</em> 541 (January): 58–61. <a href="https://doi.org/10.1038/nature20797">https://doi.org/10.1038/nature20797</a>.
</div>
<div id="ref-chen_OneoffRepeatingFast_2022" class="csl-entry" role="listitem">
Chen, Hao-Yan, Wei-Min Gu, Mouyuan Sun, and Tuan Yi. 2022. <span>“One-Off and <span>Repeating Fast Radio Bursts</span>: <span>A Statistical Analysis</span>.”</span> <em>The Astrophysical Journal</em> 939 (November): 27. <a href="https://doi.org/10.3847/1538-4357/ac958a">https://doi.org/10.3847/1538-4357/ac958a</a>.
</div>
<div id="ref-cui_FastRadioBursts_2021" class="csl-entry" role="listitem">
Cui, Xiang-Han, Cheng-Min Zhang, Shuang-Qiang Wang, Jian-Wei Zhang, Di Li, Bo Peng, Wei-Wei Zhu, Na Wang, et al. 2021. <span>“Fast Radio Bursts: Do Repeaters and Non-Repeaters Originate in Statistically Similar Ensembles?”</span> <em>Monthly Notices of the Royal Astronomical Society</em> 500 (January): 3275–80. <a href="https://doi.org/10.1093/mnras/staa3351">https://doi.org/10.1093/mnras/staa3351</a>.
</div>
<div id="ref-cui_StatisticalPropertiesFast_2021" class="csl-entry" role="listitem">
Cui, Xiang-Han, Cheng-Min Zhang, Shuang-Qiang Wang, Jian-Wei Zhang, Di Li, Bo Peng, Wei-Wei Zhu, Richard Strom, et al. 2021. <span>“Statistical Properties of Fast Radio Bursts Elucidate Their Origins: Magnetars Are Favored over Gamma-Ray Bursts.”</span> <em>Research in Astronomy and Astrophysics</em> 21 (8): 211. <a href="https://doi.org/10.1088/1674-4527/21/8/211">https://doi.org/10.1088/1674-4527/21/8/211</a>.
</div>
<div id="ref-hewitt_AreciboObservationsBurst_2022" class="csl-entry" role="listitem">
Hewitt, D. M., M. P. Snelders, J. W. T. Hessels, K. Nimmo, J. N. Jahns, L. G. Spitler, K. Gourdji, et al. 2022. <span>“Arecibo Observations of a Burst Storm from <span>FRB 20121102A</span> in 2016.”</span> <em>Monthly Notices of the Royal Astronomical Society</em> 515 (September): 3577–96. <a href="https://doi.org/10.1093/mnras/stac1960">https://doi.org/10.1093/mnras/stac1960</a>.
</div>
<div id="ref-jahns_FRB20121102ANovember_2022" class="csl-entry" role="listitem">
Jahns, J. N., L. G. Spitler, K. Nimmo, D. M. Hewitt, M. P. Snelders, A. Seymour, J. W. T. Hessels, K. Gourdji, D. Michilli, and G. H. Hilmarsson. 2022. <span>“The <span>FRB 20121102A November</span> Rain in 2018 Observed with the <span>Arecibo Telescope</span>.”</span> <em>Monthly Notices of the Royal Astronomical Society</em> 519 (November): 666–87. <a href="https://doi.org/10.1093/mnras/stac3446">https://doi.org/10.1093/mnras/stac3446</a>.
</div>
<div id="ref-katz_AbsencePeriodicityRepeating_2022" class="csl-entry" role="listitem">
Katz, J. I. 2022. <span>“The Absence of Periodicity in Repeating <span>FRB</span>.”</span> <em>Monthly Notices of the Royal Astronomical Society</em> 513 (June): 1925–31. <a href="https://doi.org/10.1093/mnras/stac1059">https://doi.org/10.1093/mnras/stac1059</a>.
</div>
<div id="ref-lin_BURSTTBustlingUniverse_2022" class="csl-entry" role="listitem">
Lin, Hsiu-Hsien, Kai-yang Lin, Chao-Te Li, Yao-Huan Tseng, Homin Jiang, Jen-Hung Wang, Jen-Chieh Cheng, et al. 2022. <span>“<span>BURSTT</span>: <span>Bustling Universe Radio Survey Telescope</span> in <span>Taiwan</span>.”</span> <em>Publications of the Astronomical Society of the Pacific</em> 134 (September): 094106. <a href="https://doi.org/10.1088/1538-3873/ac8f71">https://doi.org/10.1088/1538-3873/ac8f71</a>.
</div>
<div id="ref-lomb_LeastSquaresFrequencyAnalysis_1976" class="csl-entry" role="listitem">
Lomb, N. R. 1976. <span>“Least-<span>Squares Frequency Analysis</span> of <span>Unequally Spaced Data</span>.”</span> <em>Astrophysics and Space Science</em> 39 (February): 447–62. <a href="https://doi.org/10.1007/BF00648343">https://doi.org/10.1007/BF00648343</a>.
</div>
<div id="ref-lorimer_BrightMillisecondRadio_2007" class="csl-entry" role="listitem">
Lorimer, D. R., M. Bailes, M. A. McLaughlin, D. J. Narkevic, and F. Crawford. 2007. <span>“A Bright Millisecond Radio Burst of Extragalactic Origin.”</span> <em>Science</em> 318 (5851): 777–80. <a href="https://doi.org/10.1126/science.1147532">https://doi.org/10.1126/science.1147532</a>.
</div>
<div id="ref-luo_MachineLearningClassification_2022" class="csl-entry" role="listitem">
Luo, Jia-Wei, Jia-Ming Zhu-Ge, and Bing Zhang. 2022. <span>“Machine <span>Learning Classification</span> of <span>CHIME</span> Fast Radio Bursts: <span>I</span>. <span>Supervised Methods</span>.”</span> <em>Monthly Notices of the Royal Astronomical Society</em>, November, stac3206. <a href="https://doi.org/10.1093/mnras/stac3206">https://doi.org/10.1093/mnras/stac3206</a>.
</div>
<div id="ref-petroff_FastRadioBursts_2019" class="csl-entry" role="listitem">
Petroff, E., J. W. T. Hessels, and D. R. Lorimer. 2019. <span>“Fast Radio Bursts.”</span> <em>The Astronomy and Astrophysics Review</em> 27 (1): 75. <a href="https://doi.org/10.1007/s00159-019-0116-6">https://doi.org/10.1007/s00159-019-0116-6</a>.
</div>
<div id="ref-petroff_FastRadioBursts_2022" class="csl-entry" role="listitem">
———. 2022. <span>“Fast Radio Bursts at the Dawn of the 2020s.”</span> <em>The Astronomy and Astrophysics Review</em> 30 (1): 49. <a href="https://doi.org/10.1007/s00159-022-00139-w">https://doi.org/10.1007/s00159-022-00139-w</a>.
</div>
<div id="ref-platts_LivingTheoryCatalogue_2019" class="csl-entry" role="listitem">
Platts, E., A. Weltman, A. Walters, S. P. Tendulkar, J. E. B. Gordin, and S. Kandhai. 2019. <span>“A <span>Living Theory Catalogue</span> for <span>Fast Radio Bursts</span>.”</span> <em>Physics Reports</em> 821 (August): 1–27. <a href="https://doi.org/10.1016/j.physrep.2019.06.003">https://doi.org/10.1016/j.physrep.2019.06.003</a>.
</div>
<div id="ref-pleunis_FastRadioBurst_2021" class="csl-entry" role="listitem">
Pleunis, Ziggy, Deborah C. Good, Victoria M. Kaspi, Ryan Mckinven, Scott M. Ransom, Paul Scholz, Kevin Bandura, et al. 2021. <span>“Fast <span>Radio Burst Morphology</span> in the <span>First CHIME</span>/<span>FRB Catalog</span>.”</span> <em>The Astrophysical Journal</em> 923 (1): 1. <a href="https://doi.org/10.3847/1538-4357/ac33ac">https://doi.org/10.3847/1538-4357/ac33ac</a>.
</div>
<div id="ref-rajwade_PossiblePeriodicActivity_2020" class="csl-entry" role="listitem">
Rajwade, K M, M B Mickaliger, B W Stappers, V Morello, D Agarwal, C G Bassa, R P Breton, et al. 2020. <span>“Possible Periodic Activity in the Repeating <span>FRB</span> 121102.”</span> <em>Monthly Notices of the Royal Astronomical Society</em> 495 (4): 3551–58. <a href="https://doi.org/10.1093/mnras/staa1237">https://doi.org/10.1093/mnras/staa1237</a>.
</div>
<div id="ref-ravi_FastRadioBurst_2019" class="csl-entry" role="listitem">
Ravi, V., M. Catha, L. D’Addario, S. G. Djorgovski, G. Hallinan, R. Hobbs, J. Kocz, et al. 2019. <span>“A Fast Radio Burst Localized to a Massive Galaxy.”</span> <em>Nature</em> 572 (August): 352–54. <a href="https://doi.org/10.1038/s41586-019-1389-7">https://doi.org/10.1038/s41586-019-1389-7</a>.
</div>
<div id="ref-sand_CHIMEFRBStudy_2023" class="csl-entry" role="listitem">
Sand, Ketan R., Daniela Breitman, Daniele Michilli, Victoria M. Kaspi, Pragya Chawla, Emmanuel Fonseca, Ryan Mckinven, et al. 2023. <span>“A <span>CHIME</span>/<span>FRB</span> Study of Burst Rate and Morphological Evolution of the Periodically Repeating <span>FRB 20180916B</span>.”</span> <em>arXiv e-Prints</em>. <a href="https://doi.org/10.48550/arXiv.2307.05839">https://doi.org/10.48550/arXiv.2307.05839</a>.
</div>
<div id="ref-scargle_StudiesAstronomicalTime_1982" class="csl-entry" role="listitem">
Scargle, J. D. 1982. <span>“Studies in Astronomical Time Series Analysis. <span>II</span>. <span>Statistical</span> Aspects of Spectral Analysis of Unevenly Spaced Data.”</span> <em>The Astrophysical Journal</em> 263 (December): 835–53. <a href="https://doi.org/10.1086/160554">https://doi.org/10.1086/160554</a>.
</div>
<div id="ref-stellingwerf_PeriodDeterminationUsing_1978" class="csl-entry" role="listitem">
Stellingwerf, R. F. 1978. <span>“Period Determination Using Phase Dispersion Minimization.”</span> <em>The Astrophysical Journal</em> 224 (September): 953–60. <a href="https://doi.org/10.1086/156444">https://doi.org/10.1086/156444</a>.
</div>
<div id="ref-thechimefrbcollaborationFirstCHIMEFRB2021" class="csl-entry" role="listitem">
The CHIME/FRB Collaboration, Mandana Amiri, Bridget C. Andersen, Kevin Bandura, Sabrina Berger, Mohit Bhardwaj, Michelle M. Boyce, et al. 2021. <span>“The <span>First CHIME</span>/<span>FRB Fast Radio Burst Catalog</span>.”</span> <em>The Astrophysical Journal Supplement Series</em> 257 (2): 59. <a href="https://doi.org/10.3847/1538-4365/ac33ab">https://doi.org/10.3847/1538-4365/ac33ab</a>.
</div>
<div id="ref-thechimefrbcollaborationPeriodicActivityFast2020" class="csl-entry" role="listitem">
The CHIME/FRB Collaboration, M. Amiri, B. C. Andersen, K. M. Bandura, M. Bhardwaj, P. J. Boyle, C. Brar, et al. 2020. <span>“Periodic Activity from a Fast Radio Burst Source.”</span> <em>Nature</em> 582 (7812): 351–55. <a href="https://doi.org/10.1038/s41586-020-2398-2">https://doi.org/10.1038/s41586-020-2398-2</a>.
</div>
<div id="ref-thechimefrbcollaborationCHIMEFastRadio2018" class="csl-entry" role="listitem">
The CHIME/FRB Collaboration, M. Amiri, K. Bandura, P. Berger, M. Bhardwaj, M. M. Boyce, P. J. Boyle, et al. 2018. <span>“The <span>CHIME Fast Radio Burst Project</span>: <span>System Overview</span>.”</span> <em>The Astrophysical Journal</em> 863 (1): 48. <a href="https://doi.org/10.3847/1538-4357/aad188">https://doi.org/10.3847/1538-4357/aad188</a>.
</div>
<div id="ref-vanderplas_UnderstandingLombScargle_2018" class="csl-entry" role="listitem">
VanderPlas, Jacob T. 2018. <span>“Understanding the <span>Lomb</span>.”</span> <em>The Astrophysical Journal Supplement Series</em> 236 (1): 16. <a href="https://doi.org/10.3847/1538-4365/aab766">https://doi.org/10.3847/1538-4365/aab766</a>.
</div>
<div id="ref-zhang_StatisticalSimilarityRepeating_2022" class="csl-entry" role="listitem">
Zhang, Kongjun, Longbiao Li, Zhibin Zhang, Qinmei Li, Juanjuan Luo, and Min Jiang. 2022. <span>“The <span>Statistical Similarity</span> of <span>Repeating</span> and <span>Non-Repeating Fast Radio Bursts</span>.”</span> <em>Universe</em> 8 (7): 355. <a href="https://doi.org/10.3390/universe8070355">https://doi.org/10.3390/universe8070355</a>.
</div>
<div id="ref-zhu-ge_MachineLearningClassification_2022" class="csl-entry" role="listitem">
Zhu-Ge, Jia-Ming, Jia-Wei Luo, and Bing Zhang. 2022. <span>“Machine <span>Learning Classification</span> of <span>Fast Radio Bursts</span>: <span>II</span>. <span>Unsupervised Methods</span>.”</span> <span>arXiv</span>. <a href="https://doi.org/10.48550/arXiv.2210.02471">https://doi.org/10.48550/arXiv.2210.02471</a>.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p><a href="https://www.chime-frb.ca/catalog" class="uri">https://www.chime-frb.ca/catalog</a><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p><a href="https://www.chime-frb.ca/repeater_catalog" class="uri">https://www.chime-frb.ca/repeater_catalog</a><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p><a href="https://www.chime-frb.ca/catalog" class="uri">https://www.chime-frb.ca/catalog</a><a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p><a href="https://docs.astropy.org/en/stable/api/astropy.timeseries.LombScargle.html" class="uri">https://docs.astropy.org/en/stable/api/astropy.timeseries.LombScargle.html</a><a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p><a href="https://github.com/ckm3/Py-PDM" class="uri">https://github.com/ckm3/Py-PDM</a><a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>