---
title: "Periodictity of FRB Repeaters with Limited Sample"
authors: 
  - name: Murthadza Aznam
    affiliation: Universiti Malaya
  - Zamri Zainal Abidin
  - Norsiah Hashim
format:
  pdf:
    documentclass: article
# execute:
#     kernel: 'jupyter'
bibliography: bibliography.bib
---

<!-- 
# Considerations
- [x] Min period = 3
- [x] Max period = half observation time
- [x] Freq grid = 100_000
- [x] Sampling time (daily)
- [x] Periodograms
  - [x] Lomb-Scargle
    - [x] Error estimation using leave-one-out
  - [x] Duty Cycle
    - [x] Error estimation using leave-one-out
  - [x] Phase Dispersion Minimization
    - [ ] Error estimation using leave-one-out
- [ ] Waiting time distribution
- [ ] Evolution
  - [ ] Morphology (Sigma or Tau)
  - [ ] Flux
  - [ ] Width
  - [ ] Energy

# Subjects
- [ ] Known Repeaters
  - [ ] FRB20180916B
- [ ] New Repeaters 
  - [ ] New repeater with more detections (FRB20201130A?)
  - [ ] FRB20190915D (Good example) 10 detections
  - [ ] FRB20191106C (Bad example) 7 detections
- [ ] Known repeaters with limited samples
  - [ ] FRB20180916B with
    - [ ] 0.25*Period window
    - [ ] 0.5*Period window
    - [ ] 1*Period window
    - [ ] 2*Period window
    - [ ] 3*Period window
-->

# Introduction

# Methodology

## Dataset
This paper will use data of new repeaters, FRB20190915D and FRB20191106C, from the CHIME/FRB Catalog 2023^[<https://www.chime-frb.ca/repeater_catalog>] [@andersen_CHIMEFRBDiscovery_2023].
This paper will also use data from CHIME/FRB Catalog 1^[<https://www.chime-frb.ca/catalog>] [@thechimefrbcollaborationFirstCHIMEFRB2021] for its observation on FRB20180916B.

## Periodogram
A periodogram is a function of cost versus periods which quantifies the strength of the fit between the given period and the time series data.
The cost function depends on the method of choice.
The best period is chosen based on the period with the maximum or minimum cost.
While most periodogram methods choose the best period via the maximum cost, the phase dispersion minimization method chooses the minimum cost.
@vanderplas_UnderstandingLombScargle_2018 includes four types of periodograms: (1) Fourier Method, based on Fourier transforms; (2) Phase-Folding Method, which calculates cost by trying to fold phases at multiple trial periods; (3) Least-Square Method, which fits a model time series; and (4) Bayesian Approaches, which applies Bayesian probability to the problem.

### Method: Lomb--Scargle Periodogram
The Lomb--Scargle periodogram [@lomb_LeastSquaresFrequencyAnalysis_1976, @scargle_StudiesAstronomicalTime_1982] is the most commonly used in astronomy.
The cost function for this periodogram is the Fourier power which is to be maximized.
As such, it is a periodogram based on Fourier transform but it can also be approached as a least square optimization [@vanderplas_UnderstandingLombScargle_2018].
The widespread use of this method warrants its place in the `astropy` package^[<https://docs.astropy.org/en/stable/api/astropy.timeseries.LombScargle.html>], an astronomy package for the Python programming language.

### Method: Duty Cycle
The Duty Cycle method is a phase--folding periodogram which measures the trial period with the longest continuous inactivity per cycle of a given FRB.
This method was introduced by @rajwade_PossiblePeriodicActivity_2020 to measure the periodicity of FRB20121102A because of the nature of repeaters to be active within a certain period per cycle.
A duty cycle of 56% means that there is a continuous inactivity for 44% of the cycle.

### Method: Phase Dispersion Minimization
Phase Dispersion Minimization (PDM) is a phase--folding method to determine the periodicity of non--sinusoidal time variation introduced by @stellingwerf_PeriodDeterminationUsing_1978. 
This method computes the variances, `theta`, of the data with respect to mean light curve at each trial periods and minimizes it.
It is suitable for small dataset with irregularly sampled observations, such as the repeaters sampled in the CHIME/FRB 2023 Catalog.
This paper will use the Python wrapper of this algorithm written in C using the `py-pdm`^[<https://github.com/ckm3/Py-PDM>] package.

### Parameter: Frequency Grid
For this study, we chose a frequency grid of $f_\text{max}$ = (3 days)^-1^ to $f_\text{min} = 0.5 * ( T_\text{obs}\, \text{days})^{-1}$.
The maximum frequency is chosen such that if the period of FRBs is less than 3 days, we would see it much more often at a daily or bidaily rate.
On the other hand, the minimum frequency is chosen such that to minimize the windowing effect near the length of observation.
Following @vanderplas_UnderstandingLombScargle_2018, the frequency grid is chosen such that $N_\text{eval}=n_0T_\text{obs}f_\text{max}$ where $n_0$ is chosen to be 5.

## Uncertainty Estimation
Periodograms do not usually have an associated uncertainty, especially non-Bayesian periodograms.
As such, the Lomb--Scargle periodogram is equipped with a False Alarm Probability (FAP) associated at each power level to avoid false positives.
However, the same cannot be said about other periodograms.
It is treated with a case by case basis.
For example, @rajwade_PossiblePeriodicActivity_2020 approached the problem by calculating the full width at half maximum of the peak.

This paper will try to estimate uncertainty by employing the leave-one-out strategy.
For each event, $k$ detections of said event are used to find the best period for the chosen periodogram method.
Then, $k$ samples of $k-1$ detections are run through the same method and twice the standard deviation of best periods between these $k-1$ detections are used as the uncertainty.
The idea is that the uncertainty in the periodicity is tied to the fact that some observation might be missed.

# Result

## FRB20180916B
The methodology were first applied to FRB20180916B as a test.
The Lomb--Scargle periodogram points to a periodicity of 16.33$\pm$0.01^[The estimation results in uncertainty below 0.01] days with a false alarm probability of ... .
The Duty Cycle periodogram shows that it has a periodicity of 16.60$\pm$0.21 days with a duty cycle of 42.11% while the Phase Dispersion Minimization periodogram shows a periodicity of 16.39$\pm$ ... days.
The low uncertainty in Lomb--Scargle periodogram can be attributed to the FRB having 77 detections with a well-defined periodicity so leaving one out does not affect the result that much.
This is consistent with the accepted value of 16 days (citation needed).

## FRB20190915D
The periodicity results for FRB20190915D are 30.06$\pm$10.21 days using the Lomb--Scargle periodogram, 30.00$\pm$0.47 days using the Duty Cycle periodogram and 13.84$\pm$0.01 days using the Phase Dispersion Minimization periodogram.
Its false alarm probability is 4.87% and the duty cycle is ... .
It is surprising that phase dispersion minimization shows a different result. Why is that?

- FRB20190915D shows consistent periodicity of 30 days with false alarm probability of 1% using Lomb--Scargle periodogram and the duty cycle periodogram.
- However, the phase dispersion minimization periodogram show a different periodicity of 13.84 days with no standard deviation.
  The leave one out strategy does not yield a significant standard deviation.
  It may be because ...

## FRB20191106C
In contrast, FRB20191106C shows inconsistent result.

# Discussion

## Why does FRB20191106C show inconsistent result?
- Maybe because the waiting time is not distributed as expected.

## Why does the Phase Dispersion Minimization show different result?

## If it is indeed 30 day periodicity, why is there no more detections in the 3 year dataset?
- Possibly as second, long term periodicity.
- Possibly cataclysmic with periodic pulses.

# References
