project:
  type: website
  preview: 
      port: 4050
  render: 
      - 'index.qmd'
      # - notebooks/*
      # - 'about.qmd'
  # pre-render: 
  #   - python ./scripts/gantt.py

website:
  title: "Masters Project"
  navbar:
    right:
      - about.qmd
  #     - icon: github
  #       href: https://github.com/
  #     - icon: twitter
  #       href: https://twitter.com
format:
  html:
    theme: cosmo
    # css: styles.css
    twitter-card: true
    open-graph: true
    reader-mode: true

title-block-banner: true`