book:
  title: "Statistical Study Of Current Fast Radio Bursts (FRB) Transients (Proposal)"
  subtitle: 'SMX7001'
  chapters:
    - thesis/index.qmd
    - thesis/literature.qmd
    - thesis/methodology.qmd
    - thesis/references.qmd
  appendices: 
    - thesis/appendix/sources.qmd