project:
  type: book
  output-dir: _book
  resources: _common
  preview: 
      port: 4000
jupyter: python3
execute: 
  echo: false

book:
  subtitle: (Proposal)
  date: '22 May 2023'
  chapters:
    - index.qmd
    - thesis/literature.qmd
    - thesis/methodology.qmd
    - thesis/references.qmd
  # appendices: 
  #   - thesis/appendix/sources.qmd