project:
  type: book
  output-dir: _book
  resources: _common
  preview: 
      port: 4000
jupyter: python3
execute: 
  echo: false


format:
  pdf:
    documentclass: scrreport
    pdf-engine: pdflatex
    # template: ./_common/_templates/template.tex
  docx:
    reference-doc: ./_common/templates/template.docx

book:
  title: "Statistical Study Of Current Fast Radio Bursts (FRB) Transients"
  author: "Murthadza Aznam (S2163122)"
  date: '27 Jan 2023'
  date-format: 'DD MMM YYYY'

bibliography: ./_common/references.bib
filters: 
  - include-subchapters