[project]
name = "use-presto"
version = "0.1.0"
description = "Add your description here"
dependencies = [
    "pyslalib>=1.0.7",
    "setuptools==60",
    "presto @ git+https://github.com/scottransom/presto.git",
]
readme = "README.md"
requires-python = ">= 3.7"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.rye]
managed = true
dev-dependencies = []