book:
  title: 'A Review of the Fast Radio Bursts Literature'
  subtitle: 'SMX7001'
  chapters: 
      - index.qmd
      - properties.qmd
      - population.qmd
      - classifications.qmd
      - references.qmd