project:
  type: book
  output-dir: ../_book
  preview: 
      port: 4000
  pre-render: 
    - python ./scripts/gantt.py

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

book:
  title: "Characteristic Study Of Selected Fast Radio Bursts (FRB) Transients"
  author: "Murthadza Aznam"
  # TODO To be changed when published
  date: '2022-07-15'
  chapters:
    - index.qmd
    - literature.qmd
    - methodology.qmd
    - references.qmd

bibliography: references.bib