project:
  type: book
  output-dir: ../_book
  preview: 
      port: 4000
  pre-render: 
    - python ./scripts/gantt.py
jupyter: python3
execute: 
  echo: false


format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
    pdf-engine: pdflatex
    template: ../_templates/template.tex
  docx:
    reference-doc: ../_templates/template.docx

book:
  title: "Statistical Study Of Current Fast Radio Bursts (FRB) Transients"
  author: "Murthadza Aznam"
  date: 'now'

bibliography: references.bib