book:
  title: "Statistical Study Of Current Fast Radio Bursts (FRB) Transients (Proposal)"
  subtitle: 'SMX7001'
  chapters:
    - index.qmd
    - literature.qmd
    - methodology.qmd
    - references.qmd
  appendices: 
    - appendix/sources.qmd