# Literature Review
<!-- TODO Maths -->
<!-- TODO Beautify -->
## Observed Properties
### Dispersion Measure
As radio signals propagate through space, it interacts with mediums it encounters and thus is dispersed. As a consequence, its arrival time is directly dependent on its frequency with lower frequencies arriving later (Day, 2022; Kulkarni, 2020). The measure of this dispersion – its dispersion measure (DM) – is a key observable quantity in studies of FRBs (Keane et al., 2016).
It is generally accepted that the DM of a FRB transient is due to free electrons encountered, n_e, along the path, dl, with the relation, 
	DM= ∫_0^d▒n_e  dl.	¬(2.1)
However, it is worth noting that ionized particles, plasma temperature, magnetic fields and its relative motion contribute to this measure even though these other contributions are very small and can be neglected (Kulkarni, 2020).
The DM of a given transient is calculated using two observables: its arrival time, t, and its frequency, ν; where the DM is related by the slope relation 
	Δt=a "DM" /(Δν^2 ),	(2.2a)
or more directly 
	"DM"=KΔν^2 Δt,	(2.2b)
where a=K^(-1) and Δν^2 is the difference of the highest and lowest frequency. Users of calculation software should be made aware which conventions are used. For the sake of precision, both values with its uncertainty are provided here (Kulkarni, 2020):
a=4.148 806 4239(11) 〖"GH" 〗^2  〖"pc" 〗^(-1)  〖"cm" 〗^3  m"s" 
K=241.033 1786(66)  GHz^(-2)  pc cm^(-3)  s^(-1)

###	Fluence And Peak Flux Density
The fluence, F, of a transient is the total energy received by the antenna throughout the duration of the signal typically measured in Jansky seconds, J⋅s. It then is characterized by the expression (Petroff et al., 2019)
	F=∫_pulse▒S(t)   dt	(2.3)
where S(t) is the flux density of the signal. We can then characterize the peak flux density, S_peak and its pulse width, W_pulse like so 
	F= S_peak W_peak.	(2.4)

###	Rotation Measure
Analogous to dispersion measure, where the frequency is dispersed by the interacting medium, the radio wave may also be rotated as electrons interact with its magnetic field component. This rotation is measurable via its polarization, Θ, which is proportional to its wavelength squared, λ^2,
	Θ="RM" 〖\ λ〗^2,	(2.5)
where RM is the Faraday rotation measure. This quantity, RM, is analogous to eq. (2.1) for DM as it is the total interaction along the line of sight (Brentjens & de Bruyn, 2005; Feng et al., 2022),
	"RM"=-0.81∫_0^d▒〖B(l)_∥ n_e (l) 〗 dl.	(2.6)

## Derived Properties

### Distance Constraints
The DM of the FRBs can be used to infer the distance of the source by estimating contributions along the line of sight. FRBs typically have DM more than the contributions from Milky Way, DMMW, suggesting it is an extragalactic phenomenon. The Milky Way contribution can be calculated using an electron density model associated with eq. (2.1). The YMW16 model (Yao et al., 2017) uses known distances of pulsars using independent methods and matching it with their respective DMs. Its value highly depends on its galactic latitude as there is little material higher up in the latitude so its DM is expected to be small (Thornton et al., 2013).
Non-Milky Way contributions to the observed DM (dubbed dispersion measure excess, DME) come from the intergalactic medium (IGM) and the host galaxy (Deng & Zhang, 2014; Petroff et al., 2019),
	〖"DM" 〗_"E" ="DM"-〖"DM" 〗_"MW" =〖"DM" 〗_"IGM" +(〖"DM" 〗_"Host" /(1+z)),	(2.7)
where z is the redshift associated with the host galaxy. The DMHost of the transient depends its distance from the host galactic core and viewing angle (Thornton et al., 2013) because those factor determines how much material interacts with the signal throughout its propagation.
